project_id = "dplrumaqrdnzwzqmatqr"

[functions]
  [functions.admin-users]
    verify_jwt = false
  [functions.ai-deadhead]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.track-visit]
    verify_jwt = false
