-- Rollback for 2026-10-05-milestone-corrections.sql
-- Restores the exact value each row held before the corrections ran.
-- Verified against a full snapshot of public.songs taken at the same moment.
begin;
update public.songs set first_played = '1979-11-01' where title = 'Alabama Getaway';
update public.songs set last_played = '1995-07-09' where title = 'Alabama Getaway';
update public.songs set last_played = '1995-07-02' where title = 'All Along the Watchtower';
update public.songs set first_played = '1967-09-29' where title = 'Alligator';
update public.songs set last_played = '1971-10-31' where title = 'Alligator';
update public.songs set last_played = '1995-07-09' where title = 'Althea';
update public.songs set first_played = '1971-07-02' where title = 'Around and Around';
update public.songs set last_played = '1995-07-05' where title = 'Around and Around';
update public.songs set first_played = '1989-02-06' where title = 'Baby Blue';
update public.songs set last_played = '1995-07-09' where title = 'Baby Blue';
update public.songs set first_played = '1967-05-05' where title = 'Beat It On Down the Line';
update public.songs set last_played = '1995-07-08' where title = 'Beat It On Down the Line';
update public.songs set last_played = '1995-07-09' where title = 'Bertha';
update public.songs set first_played = '1982-07-28' where title = 'Big Boss Man';
update public.songs set last_played = '1993-06-11' where title = 'Big Boss Man';
update public.songs set first_played = '1971-02-18' where title = 'Big Railroad Blues';
update public.songs set last_played = '1995-07-05' where title = 'Big Railroad Blues';
update public.songs set first_played = '1969-01-17' where title = 'Big River';
update public.songs set last_played = '1995-07-09' where title = 'Big River';
update public.songs set last_played = '1995-07-09' where title = 'Bird Song';
update public.songs set first_played = '1986-12-15' where title = 'Black Muddy River';
update public.songs set last_played = '1995-07-09' where title = 'Black Peter';
update public.songs set last_played = '1995-06-30' where title = 'Black-Throated Wind';
update public.songs set last_played = '1995-07-06' where title = 'Blow Away';
update public.songs set first_played = '1967-10-22' where title = 'Born Cross-Eyed';
update public.songs set last_played = '1968-10-20' where title = 'Born Cross-Eyed';
update public.songs set last_played = '1995-07-09' where title = 'Brokedown Palace';
update public.songs set first_played = '1971-08-23' where title = 'Brown Eyed Women';
update public.songs set last_played = '1995-07-09' where title = 'Brown Eyed Women';
update public.songs set last_played = '1995-06-30' where title = 'Built to Last';
update public.songs set first_played = '1970-06-07' where title = 'Casey Jones';
update public.songs set last_played = '1995-07-08' where title = 'Casey Jones';
update public.songs set first_played = '1968-06-14' where title = 'China Cat Sunflower';
update public.songs set last_played = '1995-07-09' where title = 'China Cat Sunflower';
update public.songs set last_played = '1995-07-08' where title = 'China Doll';
update public.songs set first_played = '1966-07-03' where title = 'Cold Rain and Snow';
update public.songs set last_played = '1995-07-05' where title = 'Cold Rain and Snow';
update public.songs set last_played = '1995-07-05' where title = 'Comes a Time';
update public.songs set first_played = '1992-02-22' where title = 'Corrina';
update public.songs set last_played = '1995-07-08' where title = 'Corrina';
update public.songs set first_played = '1968-06-14' where title = 'Cosmic Charlie';
update public.songs set last_played = '1976-06-19' where title = 'Cosmic Charlie';
update public.songs set first_played = '1975-03-23' where title = 'Crazy Fingers';
update public.songs set last_played = '1995-07-09' where title = 'Crazy Fingers';
update public.songs set first_played = '1968-06-14' where title = 'Cryptical Envelopment';
update public.songs set last_played = '1985-11-01' where title = 'Cryptical Envelopment';
update public.songs set first_played = '1969-01-17' where title = 'Cumberland Blues';
update public.songs set last_played = '1995-07-02' where title = 'Cumberland Blues';
update public.songs set first_played = '1976-06-03' where title = 'Dancing in the Street';
update public.songs set first_played = '1968-02-14' where title = 'Dark Star';
update public.songs set last_played = '1995-07-09' where title = 'Days Between';
update public.songs set first_played = '1971-02-18' where title = 'Deal';
update public.songs set last_played = '1995-07-09' where title = 'Deal';
update public.songs set first_played = '1987-09-18' where title = 'Desolation Row';
update public.songs set last_played = '1995-03-27' where title = 'Desolation Row';
update public.songs set first_played = '1969-12-04' where title = 'Dire Wolf';
update public.songs set last_played = '1995-07-09' where title = 'Dire Wolf';
update public.songs set first_played = '1969-02-27' where title = 'Duprees Diamond Blues';
update public.songs set last_played = '1994-10-01' where title = 'Duprees Diamond Blues';
update public.songs set first_played = '1993-03-24' where title = 'Easy Answers';
update public.songs set first_played = '1969-12-04' where title = 'Easy Wind';
update public.songs set last_played = '1971-02-18' where title = 'Easy Wind';
update public.songs set first_played = '1969-08-28' where title = 'El Paso';
update public.songs set last_played = '1995-07-09' where title = 'El Paso';
update public.songs set last_played = '1995-07-09' where title = 'Estimated Prophet';
update public.songs set first_played = '1994-10-01' where title = 'Eternity';
update public.songs set last_played = '1995-07-02' where title = 'Eternity';
update public.songs set last_played = '1995-07-09' where title = 'Eyes of the World';
update public.songs set last_played = '1995-07-06' where title = 'Feel Like a Stranger';
update public.songs set first_played = '1977-03-18' where title = 'Fire on the Mountain';
update public.songs set last_played = '1995-07-09' where title = 'Fire on the Mountain';
update public.songs set first_played = '1989-02-06' where title = 'Foolish Heart';
update public.songs set last_played = '1995-07-06' where title = 'Foolish Heart';
update public.songs set first_played = '1975-06-17' where title = 'Franklin''s Tower';
update public.songs set last_played = '1995-07-09' where title = 'Franklin''s Tower';
update public.songs set last_played = '1995-07-09' where title = 'Friend of the Devil';
update public.songs set last_played = '1995-07-09' where title = 'Going Down the Road Feeling Bad';
update public.songs set first_played = '1966-07-03' where title = 'Good Lovin';
update public.songs set last_played = '1995-07-09' where title = 'Good Lovin';
update public.songs set last_played = '1995-07-05' where title = 'Greatest Story Ever Told';
update public.songs set first_played = '1969-02-27' where title = 'Hard to Handle';
update public.songs set last_played = '1990-03-29' where title = 'Hard to Handle';
update public.songs set first_played = '1972-08-27' where title = 'He''s Gone';
update public.songs set last_played = '1995-07-09' where title = 'He''s Gone';
update public.songs set first_played = '1983-10-15' where title = 'Hell in a Bucket';
update public.songs set last_played = '1995-07-09' where title = 'Hell in a Bucket';
update public.songs set first_played = '1975-06-17' where title = 'Help on the Way';
update public.songs set last_played = '1995-07-09' where title = 'Help on the Way';
update public.songs set last_played = '1974-10-18' where title = 'Here Comes Sunshine';
update public.songs set first_played = '1969-11-07' where title = 'High Time';
update public.songs set last_played = '1985-06-30' where title = 'High Time';
update public.songs set first_played = '1966-12-01' where title = 'I Know You Rider';
update public.songs set last_played = '1995-07-09' where title = 'I Know You Rider';
update public.songs set first_played = '1978-01-06' where title = 'I Need a Miracle';
update public.songs set last_played = '1995-07-08' where title = 'I Need a Miracle';
update public.songs set last_played = '1984-04-14' where title = 'In the Midnight Hour';
update public.songs set first_played = '1972-01-02' where title = 'It Must Have Been the Roses';
update public.songs set last_played = '1995-07-08' where title = 'It Must Have Been the Roses';
update public.songs set last_played = '1995-07-09' where title = 'Jack Straw';
update public.songs set last_played = '1995-07-09' where title = 'Johnny B. Goode';
update public.songs set last_played = '1995-07-08' where title = 'Just Like Tom Thumbs Blues';
update public.songs set first_played = '1989-02-06' where title = 'Just a Little Light';
update public.songs set last_played = '1995-06-24' where title = 'Just a Little Light';
update public.songs set first_played = '1982-04-06' where title = 'Keep Your Day Job';
update public.songs set last_played = '1984-07-15' where title = 'Keep Your Day Job';
update public.songs set first_played = '1987-07-04' where title = 'Knockin on Heavens Door';
update public.songs set last_played = '1995-07-09' where title = 'Knockin on Heavens Door';
update public.songs set first_played = '1984-03-31' where title = 'La Bamba';
update public.songs set last_played = '1994-12-16' where title = 'La Bamba';
update public.songs set first_played = '1976-06-03' where title = 'Lazy Lightning';
update public.songs set first_played = '1993-02-22' where title = 'Lazy River Road';
update public.songs set last_played = '1995-07-08' where title = 'Lazy River Road';
update public.songs set last_played = '1995-07-09' where title = 'Let It Grow';
update public.songs set first_played = '1993-02-22' where title = 'Liberty';
update public.songs set first_played = '1966-07-03' where title = 'Little Red Rooster';
update public.songs set last_played = '1995-07-02' where title = 'Little Red Rooster';
update public.songs set first_played = '1972-01-02' where title = 'Looks Like Rain';
update public.songs set last_played = '1995-07-05' where title = 'Looks Like Rain';
update public.songs set first_played = '1974-02-22' where title = 'Loose Lucy';
update public.songs set last_played = '1995-07-02' where title = 'Loose Lucy';
update public.songs set last_played = '1995-07-09' where title = 'Loser';
update public.songs set first_played = '1980-04-28' where title = 'Lost Sailor';
update public.songs set last_played = '1995-07-06' where title = 'Lost Sailor';
update public.songs set first_played = '1969-01-17' where title = 'Mama Tried';
update public.songs set last_played = '1995-07-08' where title = 'Mama Tried';
update public.songs set first_played = '1986-03-19' where title = 'Man Smart Woman Smarter';
update public.songs set first_played = '1969-12-04' where title = 'Mason''s Children';
update public.songs set first_played = '1966-06-11' where title = 'Me and My Uncle';
update public.songs set last_played = '1995-07-09' where title = 'Me and My Uncle';
update public.songs set first_played = '1971-10-19' where title = 'Mexicali Blues';
update public.songs set last_played = '1995-07-05' where title = 'Mexicali Blues';
update public.songs set last_played = '1995-07-09' where title = 'Might as Well';
update public.songs set first_played = '1976-06-03' where title = 'Mission in the Rain';
update public.songs set last_played = '1977-11-06' where title = 'Mission in the Rain';
update public.songs set first_played = '1972-08-27' where title = 'Mississippi Half-Step';
update public.songs set first_played = '1966-07-03' where title = 'Morning Dew';
update public.songs set last_played = '1995-07-09' where title = 'Morning Dew';
update public.songs set first_played = '1972-01-02' where title = 'Mr. Charlie';
update public.songs set last_played = '1974-06-30' where title = 'Mr. Charlie';
update public.songs set first_played = '1983-10-15' where title = 'My Brother Esau';
update public.songs set last_played = '1987-09-18' where title = 'My Brother Esau';
update public.songs set first_played = '1967-09-29' where title = 'New Potato Caboose';
update public.songs set last_played = '1968-10-20' where title = 'New Potato Caboose';
update public.songs set first_played = '1970-01-16' where title = 'New Speedway Boogie';
update public.songs set last_played = '1994-12-16' where title = 'New Speedway Boogie';
update public.songs set first_played = '1966-07-03' where title = 'Next Time You See Me';
update public.songs set last_played = '1973-02-15' where title = 'Next Time You See Me';
update public.songs set first_played = '1981-03-09' where title = 'Nobody''s Fault But Mine';
update public.songs set last_played = '1989-12-27' where title = 'Nobody''s Fault But Mine';
update public.songs set first_played = '1966-07-03' where title = 'Not Fade Away';
update public.songs set last_played = '1995-07-09' where title = 'Not Fade Away';
update public.songs set last_played = '1995-07-09' where title = 'One More Saturday Night';
update public.songs set last_played = '1995-07-06' where title = 'Peggy-O';
update public.songs set first_played = '1989-07-04' where title = 'Picasso Moon';
update public.songs set last_played = '1995-06-22' where title = 'Picasso Moon';
update public.songs set first_played = '1971-02-18' where title = 'Promised Land';
update public.songs set last_played = '1993-06-11' where title = 'Queen Jane Approximately';
update public.songs set last_played = '1995-07-09' where title = 'Ramble On Rose';
update public.songs set last_played = '1995-06-30' where title = 'Reuben and Cherise';
update public.songs set last_played = '1990-07-14' where title = 'Ripple';
update public.songs set first_played = '1969-01-17' where title = 'Rosemary';
update public.songs set last_played = '1995-07-02' where title = 'Row Jimmy';
update public.songs set first_played = '1980-04-28' where title = 'Saint of Circumstance';
update public.songs set last_played = '1995-07-06' where title = 'Saint of Circumstance';
update public.songs set first_played = '1993-09-14' where title = 'Samba in the Rain';
update public.songs set last_played = '1995-07-05' where title = 'Samba in the Rain';
update public.songs set first_played = '1966-07-03' where title = 'Satisfaction';
update public.songs set last_played = '1978-07-08' where title = 'Satisfaction';
update public.songs set last_played = '1995-07-09' where title = 'Scarlet Begonias';
update public.songs set first_played = '1978-08-31' where title = 'Shakedown Street';
update public.songs set first_played = '1987-09-18' where title = 'She Belongs to Me';
update public.songs set last_played = '1993-06-11' where title = 'She Belongs to Me';
update public.songs set last_played = '1995-07-09' where title = 'Ship of Fools';
update public.songs set first_played = '1975-06-17' where title = 'Slipknot!';
update public.songs set last_played = '1995-07-09' where title = 'Slipknot!';
update public.songs set first_played = '1992-02-22' where title = 'So Many Roads';
update public.songs set last_played = '1995-07-09' where title = 'St. Stephen';
update public.songs set first_played = '1978-01-06' where title = 'Stagger Lee';
update public.songs set last_played = '1995-07-05' where title = 'Stagger Lee';
update public.songs set last_played = '1995-07-09' where title = 'Standing on the Moon';
update public.songs set first_played = '1973-02-09' where title = 'Stella Blue';
update public.songs set last_played = '1995-07-09' where title = 'Stella Blue';
update public.songs set last_played = '1995-07-09' where title = 'Sugaree';
update public.songs set first_played = '1976-06-03' where title = 'Supplication';
update public.songs set last_played = '1995-07-01' where title = 'Supplication';
update public.songs set first_played = '1971-10-19' where title = 'Tennessee Jed';
update public.songs set last_played = '1995-07-09' where title = 'Tennessee Jed';
update public.songs set last_played = '1995-07-09' where title = 'Terrapin Station';
update public.songs set first_played = '1967-01-14' where title = 'The Golden Road';
update public.songs set last_played = '1991-09-10' where title = 'The Golden Road';
update public.songs set first_played = '1975-06-17' where title = 'The Music Never Stopped';
update public.songs set last_played = '1995-07-09' where title = 'The Music Never Stopped';
update public.songs set first_played = '1967-11-10' where title = 'The Other One';
update public.songs set last_played = '1995-07-09' where title = 'The Other One';
update public.songs set first_played = '1986-03-19' where title = 'The Race Is On';
update public.songs set last_played = '1993-09-22' where title = 'The Race Is On';
update public.songs set first_played = '1972-01-02' where title = 'The Wheel';
update public.songs set last_played = '1995-07-09' where title = 'The Wheel';
update public.songs set last_played = '1995-07-05' where title = 'They Love Each Other';
update public.songs set first_played = '1982-09-11' where title = 'Throwing Stones';
update public.songs set last_played = '1995-07-09' where title = 'Throwing Stones';
update public.songs set first_played = '1970-09-17' where title = 'To Lay Me Down';
update public.songs set last_played = '1995-06-22' where title = 'To Lay Me Down';
update public.songs set first_played = '1985-09-02' where title = 'Tons of Steel';
update public.songs set last_played = '1988-07-17' where title = 'Tons of Steel';
update public.songs set first_played = '1970-08-18' where title = 'Truckin''';
update public.songs set last_played = '1995-07-09' where title = 'Truckin''';
update public.songs set last_played = '1995-07-06' where title = 'Unbroken Chain';
update public.songs set first_played = '1969-09-01' where title = 'Uncle John''s Band';
update public.songs set last_played = '1995-07-09' where title = 'Uncle John''s Band';
update public.songs set first_played = '1989-07-04' where title = 'Victim or the Crime';
update public.songs set first_played = '1991-02-19' where title = 'Walkin Blues';
update public.songs set last_played = '1995-06-30' where title = 'Walkin Blues';
update public.songs set last_played = '1995-07-02' where title = 'Wang Dang Doodle';
update public.songs set first_played = '1994-10-01' where title = 'Way to Go Home';
update public.songs set last_played = '1995-07-08' where title = 'Way to Go Home';
update public.songs set first_played = '1968-10-12' where title = 'We Bid You Goodnight';
update public.songs set last_played = '1995-07-09' where title = 'We Bid You Goodnight';
update public.songs set first_played = '1973-09-07' where title = 'Weather Report Suite';
update public.songs set last_played = '1974-10-20' where title = 'Weather Report Suite';
update public.songs set first_played = '1978-04-11' where title = 'Werewolves of London';
update public.songs set last_played = '1993-06-11' where title = 'Werewolves of London';
update public.songs set last_played = '1995-07-09' where title = 'West L.A. Fadeaway';
update public.songs set last_played = '1995-07-09' where title = 'Wharf Rat';
update public.songs set last_played = '1993-06-11' where title = 'When I Paint My Masterpiece';
update public.songs set first_played = '1987-09-15' where title = 'When Push Comes to Shove';
update public.songs set last_played = '1992-09-17' where title = 'When Push Comes to Shove';
update public.songs set last_played = '1995-06-25' where title = 'Women Are Smarter';
commit;
