// Originally auto-generated by Lovable (Lovable Cloud auth). After migrating
// hosting off Lovable, the old flow redirected the browser to Lovable's hosted
// `/~oauth/initiate` gateway — which only existed on Lovable's hosting and now
// 404s on Netlify, breaking social sign-in.
//
// Rewired to NATIVE Supabase OAuth. The Supabase project already has the Google
// and Apple providers configured (verified against /auth/v1/authorize), so this
// removes the Lovable dependency entirely. The call sites are unchanged — they
// still call `lovable.auth.signInWithOAuth(provider, { redirect_uri })`.

import { supabase } from "../supabase/client";
import type { Provider } from "@supabase/supabase-js";

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

// Map our provider names to Supabase's (Microsoft = "azure" in Supabase).
const toSupabaseProvider = (p: "google" | "apple" | "microsoft"): Provider =>
  (p === "microsoft" ? "azure" : p) as Provider;

export const lovable = {
  auth: {
    signInWithOAuth: async (
      provider: "google" | "apple" | "microsoft",
      opts?: SignInOptions,
    ) => {
      // supabase-js redirects the browser straight to the provider; the return
      // (`?code=…`) is auto-exchanged on load via detectSessionInUrl (default on).
      const { data, error } = await supabase.auth.signInWithOAuth({
        provider: toSupabaseProvider(provider),
        options: {
          redirectTo: opts?.redirect_uri ?? window.location.origin,
          queryParams: opts?.extraParams,
        },
      });
      if (error) return { error };
      return { redirected: true, url: data?.url };
    },
  },
};
