import { forwardRef, useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Sparkles } from "lucide-react";

const DISMISS_KEY = "ds_handle_prompt_dismissed";

/**
 * Heuristic: a display_name "looks auto-generated" when it matches the
 * email's local-part for a private-relay user, OR is an opaque ≥8-char
 * vowel-less alphanumeric string, OR is one of the Dead-themed fallbacks
 * the trigger assigns (those end in a 4-digit suffix). For the fallback
 * case we only consider it "auto" if the user hasn't dismissed before —
 * we want them to be able to keep "Sugar Magnolia 4271" if they like it.
 */
const looksAutoGenerated = (name: string | null | undefined, email: string | null | undefined) => {
  if (!name) return true;
  const trimmed = name.trim();
  if (!trimmed) return true;
  const local = email ? email.split("@")[0] : "";
  if (local && trimmed === local) return true;
  if (/^[a-z0-9]{8,}$/.test(trimmed) && !/[aeiou]/.test(trimmed)) return true;
  return false;
};

const PickHandleModal = forwardRef<HTMLDivElement>((_props, _ref) => {
  const { user, loading } = useAuth();
  const [open, setOpen] = useState(false);
  const [value, setValue] = useState("");
  const [saving, setSaving] = useState(false);
  const [currentName, setCurrentName] = useState<string | null>(null);

  useEffect(() => {
    if (loading || !user) return;
    if (typeof window === "undefined") return;
    if (sessionStorage.getItem(DISMISS_KEY) === "1") return;

    let cancelled = false;
    (async () => {
      const { data: profile } = await supabase
        .from("profiles")
        .select("display_name")
        .eq("user_id", user.id)
        .maybeSingle();
      if (cancelled) return;

      const name = profile?.display_name ?? null;
      setCurrentName(name);

      if (looksAutoGenerated(name, user.email)) {
        setValue("");
        setOpen(true);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [user, loading]);

  const dismiss = () => {
    sessionStorage.setItem(DISMISS_KEY, "1");
    setOpen(false);
  };

  const handleSave = async () => {
    if (!user) return;
    const handle = value.trim();
    if (handle.length < 2 || handle.length > 40) {
      toast.error("Pick a name between 2 and 40 characters");
      return;
    }
    setSaving(true);
    const { error } = await supabase
      .from("profiles")
      .update({ display_name: handle })
      .eq("user_id", user.id);
    setSaving(false);
    if (error) {
      toast.error("Couldn't save your handle. Try again.");
      return;
    }
    toast.success(`Welcome, ${handle}`);
    sessionStorage.setItem(DISMISS_KEY, "1");
    setOpen(false);
  };

  if (!user) return null;

  return (
    <Dialog open={open} onOpenChange={(o) => { if (!o) dismiss(); }}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <div className="flex items-center gap-2 text-primary mb-2">
            <Sparkles className="w-4 h-4" />
            <span className="text-sm uppercase tracking-wider">Pick your handle</span>
          </div>
          <DialogTitle className="font-display text-2xl">
            How should the community know you?
          </DialogTitle>
          <DialogDescription className="text-base text-muted-foreground pt-2">
            {currentName && (
              <>
                You're showing up right now as{" "}
                <span className="text-foreground font-medium">"{currentName}"</span>.
                Pick a name your fellow heads will recognize on setlists, comments,
                and messages.
              </>
            )}
            {!currentName && (
              <>Pick a name your fellow heads will recognize on setlists, comments, and messages.</>
            )}
          </DialogDescription>
        </DialogHeader>

        <div className="py-4">
          <Input
            autoFocus
            value={value}
            onChange={(e) => setValue(e.target.value)}
            placeholder="e.g. Jerry from Jersey"
            maxLength={40}
            onKeyDown={(e) => {
              if (e.key === "Enter") handleSave();
            }}
          />
          <p className="text-sm text-muted-foreground mt-2">
            You can change this anytime in your Profile.
          </p>
        </div>

        <DialogFooter className="gap-2 sm:gap-2">
          <Button variant="ghost" onClick={dismiss} disabled={saving}>
            Maybe later
          </Button>
          <Button onClick={handleSave} disabled={saving || value.trim().length < 2}>
            {saving ? "Saving…" : "Save handle"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
});

PickHandleModal.displayName = "PickHandleModal";

export default PickHandleModal;
