import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

/**
 * Starting an OAuth sign-in is a protocol, and it had two implementations.
 *
 * Auth.tsx and AuthModal.tsx each held their own copy of the same dance —
 * markOAuthRedirect, set post_oauth_redirect, signInWithOAuth with a
 * redirectTo. Identical until they weren't: the native branch had to be added
 * in both places, and a copy that anyone forgets is a sign-in button that
 * silently does nothing on device. Same shape as the encodeArchiveNotes
 * divergence (see src/hooks/__tests__/encodeArchiveNotesSingleSource.test.ts).
 *
 * So this asserts the invariant that actually matters: exactly one module
 * calls supabase.auth.signInWithOAuth, and every surface goes through it.
 */

const SRC = join(process.cwd(), "src");
const CALL = /\.auth\.signInWithOAuth\s*\(/;

/** Generated by the Lovable CLI; it wraps its own SDK, not our Supabase client. */
const GENERATED = "src/integrations/lovable/index.ts";

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) return walk(full);
    return /\.tsx?$/.test(entry) ? [full] : [];
  });
}

const relative = (file: string) => file.replace(SRC, "src").replace(/\\/g, "/");

describe("OAuth sign-in has a single source of truth", () => {
  it("calls signInWithOAuth from exactly one module", () => {
    const callers = walk(SRC)
      .filter((file) => CALL.test(readFileSync(file, "utf-8")))
      .map(relative)
      .filter((file) => file !== GENERATED);

    expect(callers).toEqual(["src/lib/oauthSignIn.ts"]);
  });

  it("does not gate sign-in buttons on isNativeApp any more", () => {
    // The old shape hid Google and Apple behind `!isNative`. If that gate
    // comes back in an auth surface, the native flow below is dead code.
    const surfaces = ["src/pages/Auth.tsx", "src/components/AuthModal.tsx"];
    for (const surface of surfaces) {
      const source = readFileSync(join(process.cwd(), surface), "utf-8");
      expect(source).not.toMatch(/\{!isNative\s*&&/);
    }
  });
});
